version: '3.8'

services:
  web:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=foodhub
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: foodhub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
